apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: backend-container
          image: tessssssssy/campingontop:9.VERSION
          resources:
            requests:
              memory: "512m"
              cpu: "100m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
          envFrom:
            - configMapRef:
                name: backend-config
      terminationGracePeriodSeconds: 5